--
-- Script was generated by Devart dbForge Studio for MySQL, Version 7.1.13.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 10/25/2018 2:35:57 PM
-- Server version: 5.5.5-10.1.31-MariaDB
-- Client version: 4.1
--


-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set default database
--

--
-- Definition for table book_authors
--
DROP TABLE IF EXISTS book_authors;
CREATE TABLE book_authors (
  seq_id INT(11) NOT NULL AUTO_INCREMENT,
  author_id INT(11) NOT NULL,
  name VARCHAR(100) DEFAULT NULL,
  created_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  created_by VARCHAR(100) NOT NULL,
  updated_date TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  updated_by VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (author_id),
  UNIQUE INDEX seq_id (seq_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table book_types
--
DROP TABLE IF EXISTS book_types;
CREATE TABLE book_types (
  seq_id INT(11) NOT NULL AUTO_INCREMENT,
  type_id INT(11) NOT NULL,
  name VARCHAR(100) NOT NULL,
  created_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  created_by VARCHAR(100) DEFAULT NULL,
  updated_date TIMESTAMP NULL DEFAULT NULL,
  updated_by VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (type_id),
  UNIQUE INDEX seq_id (seq_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table books
--
DROP TABLE IF EXISTS books;
CREATE TABLE books (
  seq_id INT(11) NOT NULL,
  book_id INT(11) NOT NULL,
  title VARCHAR(255) NOT NULL,
  author_id INT(11) NOT NULL,
  date_published DATE NOT NULL,
  type_id INT(11) NOT NULL,
  created_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by VARCHAR(100) DEFAULT NULL,
  updated_date TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  updated_by VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (book_id),
  INDEX IDX_books_author_id (author_id),
  INDEX IDX_books_type_id (type_id)
)
ENGINE = INNODB
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for view book_list
--
DROP VIEW IF EXISTS book_list CASCADE;
CREATE OR REPLACE 
	DEFINER = 'root'@'localhost'
VIEW book_list
AS
	select `b`.`book_id` AS `book_id`,`b`.`title` AS `title`,`ba`.`name` AS `author_name`,`bt`.`name` AS `type`,`b`.`date_published` AS `date_published`,`b`.`created_date` AS `created_date`,`b`.`created_by` AS `created_by`,`b`.`updated_date` AS `updated_date`,`b`.`updated_by` AS `updated_by` from ((`books` `b` join `book_authors` `ba` on((`ba`.`author_id` = `b`.`author_id`))) join `book_types` `bt` on((`bt`.`type_id` = `b`.`type_id`)));

-- 
-- Dumping data for table book_authors
--
INSERT INTO book_authors VALUES
(1, 1, 'test123', '2018-10-24 17:22:31', 'admin', '2018-10-24 17:31:12', 'admin');

-- 
-- Dumping data for table book_types
--

-- Table mplus.book_types does not contain any data (it is empty)

-- 
-- Dumping data for table books
--

-- Table mplus.books does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;